/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kuresato' at '16/11/05 17:14' with Gradle 3.1
 *
 * @author kuresato, @date 16/11/05 17:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
